version: 2
jobs:
  build:
    docker:
      - image: codegram/decidim
        environment:
          SIMPLECOV: true
          DATABASE_USERNAME: postgres
      - image: postgres
        environment:
          POSTGRES_USER: postgres
    parallelism: 4
    working_directory: /code
    steps:
      - run:
          name: Install Chrome
          command: |
            apt-get update
            apt-get install -y zip unzip
            wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
            echo "deb http://dl.google.com/linux/chrome/deb/ stable main" > /etc/apt/sources.list.d/google.list
            apt-get update && apt-get install -y google-chrome-stable && rm -rf /var/lib/apt/lists/*
            cd /tmp
            wget -N http://chromedriver.storage.googleapis.com/2.26/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip
            chmod +x chromedriver
            mv -f chromedriver /usr/local/share/chromedriver
            ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
            ln -s /usr/local/share/chromedriver /usr/bin/chromedriver
            
      - checkout
      - run:
          name: Install app dependencies
          command: |
            bundle install
            yarn
      - run:
          name: Generate test app
          command: bundle exec rake decidim:generate_test_app
      - run:
          name: Precompile assets
          command: cd spec/decidim_dummy_app && bundle exec rake assets:precompile
      - run:
          name: Run tests
          command: |
            case $CIRCLE_NODE_INDEX in
              0)
                (cd /code && yarn lint && bundle exec rspec spec) &&
                (cd /code && yarn test -- decidim-api) &&
                (cd /code/decidim-api && bundle exec rake) &&
                (cd /code && yarn test -- decidim-core) &&
                (cd /code/decidim-core && bundle exec rake)
                ;;
              1)
                (cd /code && yarn test -- decidim-admin) &&
                (cd /code/decidim-admin && bundle exec rake) &&
                (cd /code && yarn test -- decidim-meetings) &&
                (cd /code/decidim-meetings && bundle exec rake)
                ;;
              2)
                (cd /code && yarn test -- decidim-proposals) &&
                (cd /code/decidim-proposals && bundle exec rake) &&
                (cd /code && yarn test -- decidim-comments) &&
                (cd /code/decidim-comments && bundle exec rake)
                ;;
              3)
                (cd /code && yarn test -- decidim-pages) &&
                (cd /code/decidim-pages && bundle exec rake) &&
                (cd /code && yarn test -- decidim-system) &&
                (cd /code/decidim-system && bundle exec rake) &&
                (cd /code && yarn test -- decidim-results) &&
                (cd /code/decidim-results && bundle exec rake) &&
                (cd /code && yarn test -- decidim-budgets) &&
                (cd /code/decidim-budgets && bundle exec rake)
                ;;
            esac
      - store_artifacts:
          path: /code/spec/decidim_dummy_app/tmp/capybara
